# xp-forge/address

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.0.0/setup' -O - | php
  - wget 'https://github.com/xp-framework/core/releases/download/v6.0.0beta2/xp-rt-6.0.0beta2.xar'
  - ls -1 *.xar > boot.pth
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - ./unittest src/test/php
